"""followers

Revision ID: 02834c826228
Revises: 1e2e3bed4bff
Create Date: 2023-02-13 11:32:21.977955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02834c826228'
down_revision = '1e2e3bed4bff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
